'use client';
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useState } from 'react';
import { useCart } from '@/context/CartContext';
import Image from 'next/image';
export default function StickyCartPanel() {
    const { cart, updateQuantity, removeFromCart } = useCart();
    const [isExpanded, setIsExpanded] = useState(false);
    if (cart.itemCount === 0)
        return null;
    return (_jsxs("div", { className: "fixed bottom-0 left-0 right-0 z-50 bg-white border-t border-gray-200 shadow-lg", children: [_jsx("div", { className: "px-4 py-3 cursor-pointer", onClick: () => setIsExpanded(!isExpanded), children: _jsxs("div", { className: "flex justify-between items-center", children: [_jsxs("div", { className: "flex items-center space-x-3", children: [_jsx("div", { className: "bg-green-600 text-white rounded-full w-6 h-6 flex items-center justify-center text-sm font-bold", children: cart.itemCount }), _jsxs("span", { className: "font-semibold text-gray-800", children: [cart.itemCount, " item", cart.itemCount > 1 ? 's' : '', " in cart"] })] }), _jsxs("div", { className: "flex items-center space-x-4", children: [_jsxs("span", { className: "text-lg font-bold text-green-600", children: ["KSh ", cart.total.toLocaleString()] }), _jsx("button", { className: "bg-green-600 hover:bg-green-700 text-white px-6 py-2 rounded-lg font-semibold transition-colors", onClick: (e) => {
                                        e.stopPropagation();
                                        // Navigate to checkout
                                        window.location.href = '/checkout';
                                    }, children: "Checkout" })] })] }) }), isExpanded && (_jsx("div", { className: "border-t border-gray-100 max-h-96 overflow-y-auto", children: _jsx("div", { className: "p-4 space-y-3", children: cart.items.map((item) => (_jsxs("div", { className: "flex items-center space-x-3 bg-gray-50 p-3 rounded-lg", children: [_jsx("div", { className: "w-12 h-12 relative", children: _jsx(Image, { src: item.image, alt: item.name, fill: true, style: { objectFit: 'cover' }, className: "rounded" }) }), _jsxs("div", { className: "flex-1", children: [_jsx("h4", { className: "font-medium text-sm text-gray-800", children: item.name }), _jsx("p", { className: "text-xs text-gray-600", children: item.weight }), _jsxs("p", { className: "text-sm font-semibold text-green-600", children: ["KSh ", item.price.toLocaleString()] })] }), _jsxs("div", { className: "flex items-center space-x-2", children: [_jsx("button", { onClick: () => updateQuantity(item.id, item.weight, item.quantity - 1), className: "w-8 h-8 rounded-full bg-gray-200 flex items-center justify-center text-gray-600 hover:bg-gray-300", children: "-" }), _jsx("span", { className: "w-8 text-center font-medium", children: item.quantity }), _jsx("button", { onClick: () => updateQuantity(item.id, item.weight, item.quantity + 1), className: "w-8 h-8 rounded-full bg-green-600 flex items-center justify-center text-white hover:bg-green-700", children: "+" })] }), _jsx("button", { onClick: () => removeFromCart(item.id, item.weight), className: "text-red-500 hover:text-red-700 p-1", title: "Remove item", children: "\u00D7" })] }, `${item.id}-${item.weight}`))) }) }))] }));
}
